version: "3"
services:

  db:
    #image: postgres
    build: ./src_postgres
    env_file:
      - variables.env
    restart: unless-stopped
    ports:
      - "5432"
    volumes:
      - wikijs_db:/var/lib/postgresql/data
      - ./sqldumps:/var/lib/postgresql/sqldumps

  wiki:
    #image: requarks/wiki:2
    build: ./src_wiki
    env_file:
      - variables.env
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - wikijs_data:/wiki/data

volumes:
  wikijs_db:
  wikijs_data:
