FROM requarks/wiki:2

## istruzione necessaria in fase di build con popolamento del db con dati pregressi.
## il processo di inizializzazione del db vuoto riesce a crearla, in caso contrario meglio crearla manualmente per evitare "permission denied"
RUN mkdir -p /wiki/data/uploads